export const fields = {
  fullName: 'Họ và tên',
  code: 'Mã hồ sơ',
  department: 'Đơn vị',
  position: 'Chức vụ',
  role: 'Vai trò',
  gender: 'Giới tính',
  birthday: 'Ngày sinh',
  otherName: 'Tên gọi khác',
  height: 'Chiều cao',
  weight: 'Cân nặng',
  baseUnit: 'Đơn vị cơ sở',
  religion: 'Tôn giáo',
  ethnicity: 'Dân tộc',
  bloodType: 'Nhóm máu',
  birthPlace: 'Nơi sinh',
  phoneNumber: 'Số điện thoại',
  healthStatus: 'Tình trạng sức khoẻ',
  indentityCard: 'Số CMND/CCCD',
  placeOfIssue: 'Nơi cấp',
  affiliatedUnit: 'Đơn vị công tác',
  dutyId: 'Chức vụ',
  province: 'Tỉnh',
};
